var backtrack = require('./../src/backtrack.js');
var subject = new backtrack.model();
subject.setRoot(9,10);
subject.setRoot(10,9);
subject.onTrack(10,11);
subject.onTrack(11,10);
subject.rootVisited(11,11);
subject.rootVisited(12,12);
subject.getDirection('','');
subject.forwardSearch(subject.tree,9,10);
subject.forwardSearch(subject.tree,9,9);
subject.forwardSearch(subject.tree,10,10);
subject.forwardTraverse(subject.tree,'');
subject.forwardTraverse(subject.tree,'');
subject.backwardSearch(subject.tree,11,10);
subject.backwardSearch(subject.tree,10,11);
subject.backwardSearch(subject.tree,9,12);
subject.backwardTraverse(subject.tree,'');
subject.backwardTraverse(subject.tree,'');
